{
 "title": "Hubble / HTTP connectivity / Namespace",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "namespace",
    "label": "Destination Namespace",
    "query": {
     "query": "label_values(hubble_http_requests_total, destination_namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Service Map",
   "type": "nodeGraph",
   "gridPos": { "h": 22, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "serviceMapQuery": { "destinationNamespace": "${namespace}", "sourceNamespace": ".*" }
    }
   ]
  },
  {
   "title": "HTTP request rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_http_requests_total{source!=\"\",destination!=\"\",destination_namespace=\"${namespace}\"}[$__rate_interval])) by (source,destination) > 0",
     "legendFormat": "{{source}} -> {{destination}}",
     "serviceMapQuery": { "destinationNamespace": ".*", "sourceNamespace": ".*" }
    }
   ]
  },
  {
   "title": "HTTP failed (5xx) requests",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(hubble_http_requests_total{source!=\"\",destination!=\"\",status=~\"5.*\",destination_namespace=\"${namespace}\"}[$__rate_interval])) by (source,destination,status) > 0",
     "legendFormat": "{{source}} -> {{destination}} ({{status}})",
     "serviceMapQuery": { "destinationNamespace": ".*", "sourceNamespace": ".*" }
    }
   ]
  },
  {
   "title": "Median HTTP request duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(hubble_http_request_duration_seconds_bucket{source!=\"\",destination!=\"\",destination_namespace=\"${namespace}\"}[$__rate_interval])) by (le,source,destination))",
     "legendFormat": "{{source}} -> {{destination}}",
     "serviceMapQuery": { "destinationNamespace": ".*", "sourceNamespace": ".*" }
    }
   ]
  },
  {
   "title": "90th percentile HTTP request duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, sum(rate(hubble_http_request_duration_seconds_bucket{source!=\"\",destination!=\"\",destination_namespace=\"${namespace}\"}[$__rate_interval])) by (le,source,destination))",
     "legendFormat": "{{source}} -> {{destination}}",
     "serviceMapQuery": { "destinationNamespace": ".*", "sourceNamespace": ".*" }
    }
   ]
  }
 ]
}